server:
  port: 9000
  # ONLY FOR TESTING
  servlet:
    session:
      cookie:
        http-only: false
        secure: false

spring:
  application:
    name: bobr-auth
  mvc:
    log-request-details: true

logging:
  level:
    root: info
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.web.cors: INFO
    org.apache.catalina.filters.RequestDumperFilter: DEBUG

bobr-front:
  base-uri: 'http://127.0.0.1:3000'
bobr-auth:
  base-uri: 'http://127.0.0.1:9000'
oauth2:
  client-id: 'client'
  client-secret: '{noop}secret'